name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker container to Github Package Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/langaracpsc/links:latest
            
  deployment: 
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker package on LCSC server
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://watchtower.langaracs.ca/v1/update'
          method: 'GET'
          bearerToken: ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}
          timeout: 20000
